apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}-client
  labels:
    app: {{ template "name" . }}
    release: {{ .Release.Name }}
    version: {{ .Chart.Version }}
    role: client
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: "{{ .Release.Service }}"
spec:
  replicas: {{ .Values.client.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "name" . }}
        release: "{{ .Release.Name }}"
        role: client
      annotations:
        productID: "{{ .Values.cluster.productID }}"
        productName: "{{ .Values.cluster.productName }}"
        productVersion: "{{ .Values.cluster.productVersion }}"
    spec:
      affinity:
      {{- include "nodeaffinity" . | indent 6 }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
{{ toYaml .Values.client.resources | indent 12 }}
          env:
            - name: LICENSE
              value: "accept"
            - name: HOST_ROLE
              value: "CLIENT"
          ports:
            - containerPort: {{ .Values.client.sshPort }}
          securityContext:
            capabilities:
              add:
                - SYS_NICE
                - NET_BIND_SERVICE
          volumeMounts:
            - mountPath: /shared
              name: persistdir
      volumes:
        - name: persistdir
          persistentVolumeClaim:
          {{- if .Values.cluster.pvc.existingClaimName }}
            claimName: {{ .Values.cluster.pvc.existingClaimName }}
          {{- else }}
            claimName: {{ template "fullname" . }}
          {{- end }}
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
