apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}-master
  labels:
    app: {{ template "name" . }}
    release: {{ .Release.Name }}
    version: {{ .Chart.Version }}
    role: master
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: "{{ .Release.Service }}"
spec:
  replicas: {{ .Values.master.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "name" . }}
        release: "{{ .Release.Name }}"
        role: master
      annotations:
        productName: "IBM Spectrum Symphony"
        productVersion: "7.2"
        productID: "IBMSpectrumSymphony_5725G86_72_CE_000"
    spec:
     affinity:
     {{- include "nodeaffinity" . | indent 6 }}
     containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
{{ toYaml .Values.master.resources | indent 12 }}
          env:
            - name: LICENSE
              value: "accept"
            - name: CLUSTER_NAME
              value: "{{ .Values.cluster.clustertName }}"
            {{- if .Values.master.regenSSLCert }}
            - name: GENERATE_SSL_CERT
              value: "Y"
            {{- end }}
            {{- if .Values.cluster.enableSSHD }}
            - name: START_SSHD
              value: "Y"
            {{- end }}
          ports:
            {{- if .Values.master.uiEnabled }}
            - containerPort: 8443
            {{- end }}
            {{- if .Values.master.uiEnabled }}
            - containerPort: 8543
            {{- end }}
            {{- if .Values.master.uiEnabled }}
            - containerPort: 8050
            {{- end }}
          securityContext:
            capabilities:
              add:
                - LEASE
                - NET_ADMIN
                - NET_BIND_SERVICE
                - NET_BROADCAST
                - SETGID
                - SETUID
                - SYS_ADMIN
                - SYS_CHROOT
                - SYS_NICE
                - SYS_RESOURCE
                - SYS_TIME
          volumeMounts:
            - mountPath: /shared
              name: persistdir
     volumes:
       - name: persistdir
         persistentVolumeClaim:
         {{- if .Values.cluster.pvc.existingClaimName }}
           claimName: {{ .Values.cluster.pvc.existingClaimName }}
         {{- else }}
           claimName: {{ template "fullname" . }}
         {{- end }}
     restartPolicy: Always
     terminationGracePeriodSeconds: 30
