apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}-compute
  labels:
    app: {{ template "name" . }}
    release: {{ .Release.Name }}
    version: {{ .Chart.Version }}
    role: compute
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: "{{ .Release.Service }}"
spec:
  replicas: {{ .Values.compute.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "name" . }}
        release: "{{ .Release.Name }}"
        role: compute
      annotations:
        productName: "IBM Spectrum Symphony"
        productVersion: "7.2"
        productID: "IBMSpectrumSymphony_5725G86_72_CE_000"
    spec:
      affinity:
      {{- include "nodeaffinity" . | indent 6 }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
{{ toYaml .Values.compute.resources | indent 12 }}
          env:
            - name: LICENSE
              value: "accept"
            - name: HOST_ROLE
              value: "COMPUTE"
            {{- if .Values.cluster.enableSSHD }}
            - name: START_SSHD
              value: "Y"
            {{- end }}
          securityContext:
            capabilities:
              add:
                - SYS_NICE
                - NET_BIND_SERVICE
          volumeMounts:
            - mountPath: /shared
              name: persistdir
      volumes:
        - name: persistdir
          persistentVolumeClaim:
          {{- if .Values.cluster.pvc.existingClaimName }}
            claimName: {{ .Values.cluster.pvc.existingClaimName }}
          {{- else }}
            claimName: {{ template "fullname" . }}
          {{- end }}
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
