{{- if .Values.compute.usePodAutoscaler }}
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "name" . }}
    release: {{ .Release.Name }}
    version: {{ .Chart.Version }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: "{{ .Release.Service }}"
spec:
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: {{ template "fullname" . }}-compute
  minReplicas: {{ .Values.compute.minReplicas }}
  maxReplicas: {{ .Values.compute.maxReplicas }}
  targetCPUUtilizationPercentage: {{ .Values.compute.targetCPUUtilizationPercentage }}
{{- end }}
