apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}-master
  labels:
    app: {{ template "name" . }}
    release: {{ .Release.Name }}
    version: {{ .Chart.Version }}
    role: master
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: "{{ .Release.Service }}"
spec:
  type: {{ .Values.master.serviceType }}
  ports:
    - name: {{ .Values.master.uiName }}
      protocol: {{ .Values.master.uiProto }}
      port: {{ .Values.master.uiPort }}
      targetPort: {{ .Values.master.uiTargetPort }}
    - name: {{ .Values.master.egoRestName }}
      protocol: {{ .Values.master.egoRestProto }}
      port: {{ .Values.master.egoRestPort }}
      targetPort: {{ .Values.master.egoRestTargetPort }}
    - name: {{ .Values.master.symRestName }}
      protocol: {{ .Values.master.symRestProto }}
      port: {{ .Values.master.symRestPort }}
      targetPort: {{ .Values.master.symRestTargetPort }}
  selector:
    app: {{ template "name" . }}
    release: {{ .Release.Name }}
    role: master
