apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}-master
  labels:
    app: {{ template "name" . }}
    release: {{ .Release.Name }}
    version: {{ .Chart.Version }}
    role: master
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: "{{ .Release.Service }}"
spec:
  type: NodePort
  ports:
{{- if .Values.master.uiEnabled }}
    - name: webgui
      protocol: TCP
      port: 8443
      targetPort: 8443
{{- end }}
{{- if .Values.master.egoRestEnabled }}
    - name: egorest
      protocol: TCP
      port: 8543
      targetPort: 8543
{{- end }}
{{- if .Values.master.symRestEnabled }}
    - name: symrest
      protocol: TCP
      port: 8050
      targetPort: 8050
{{- end }}
  selector:
    app: {{ template "name" . }}
    release: {{ .Release.Name }}
    role: master
