apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}-client
  labels:
    app: {{ template "name" . }}
    release: {{ .Release.Name }}
    version: {{ .Chart.Version }}
    role: client
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: "{{ .Release.Service }}"
spec:
  type: {{ .Values.client.serviceType }}
  ports:
    - name: {{ .Values.client.sshName }}
      protocol: {{ .Values.client.sshProto }}
      port: {{ .Values.client.sshPort }}
      targetPort: {{ .Values.client.sshTargetPort }}
  selector:
    app: {{ template "name" . }}
    release: {{ .Release.Name }}
    role: client
