apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}-client
  labels:
    app: {{ template "name" . }}
    release: {{ .Release.Name }}
    version: {{ .Chart.Version }}
    role: client
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: "{{ .Release.Service }}"
spec:
  type: NodePort
  ports:
    - name: sshd
      protocol: TCP
      port: 22
      targetPort: 22
  selector:
    app: {{ template "name" . }}
    release: {{ .Release.Name }}
    role: client
