apiVersion: v1
name: ibm-mongodb-dev
version: 1.1.0
appVersion: 3.6.0
description: NoSQL document-oriented database that stores JSON-like documents with dynamic schemas, simplifying the integration of data in content-driven applications.
icon: https://na.cumulusrepo.com/assetswithkey/810a660f7d93788ead183b398b689938/mongocharticon/v1
keywords:
- mongodb
- database
- nosql
maintainers:
  - name: IBM Analytics
sources:
- https://github.com/IBM/charts/tree/master/stable
tillerVersion: ">=2.4.0"
engine: gotpl


