#####################################################################################################
######### Thirdparty containers for IBM InfoSphere Information Server for Evaluation v11.7 ##########
#####################################################################################################


cassandra: 

   image: docker.io/cassandra:3.0
   volumeClaim:
      name: "cas-pvc"
      size: 5Gi
      existingClaimName: ""
      storageClassName: "" 
      accessMode: ReadWriteOnce

zookeeper:

   image: zookeeper:3.4.10
   volumeClaim:
      name: "zk-pvc"
      size: 5Gi
      existingClaimName: ""
      storageClassName: "" 
      accessMode: ReadWriteOnce

kafka:

   image: wurstmeister/kafka:0.11.0.1
   volumeClaim:
      name: "kafka-pvc"
      size: 10Gi
      existingClaimName: ""
      storageClassName: "" 
      accessMode: ReadWriteOnce

elasticsearch:

   image: docker.elastic.co/elasticsearch/elasticsearch:5.5.2
   volumeClaim:
      name: "es-pvc"
      size: 5Gi
      existingClaimName: ""
      storageClassName: ""
      accessMode: ReadWriteOnce

logstash:

  image: docker.elastic.co/logstash/logstash:5.5.2
  volumeClaim:
      name: "log-pvc"
      size: 5Gi
      existingClaimName: ""
      storageClassName: "" 
      accessMode: ReadWriteOnce

kibana:

   image: docker.elastic.co/kibana/kibana:5.5.2
