image:
  pullPolicy: IfNotPresent

logstash:
  replicas: 1
  name: logstash
  heapSize: "256m"
  port: 5000
  image:
    repository: "ibmcom/logstash"
    tag: "5.5.1"

kibana:
  replicas: 1
  name: kibana
  internal: 5601
  external: 31601
  image:
    repository: ibmcom/kibana
    tag: 5.5.1

filebeat:
  name: filebeat-ds
  image:
    repository: "ibmcom/filebeat"
    tag: 5.5.1

elasticsearch:
  name: "elasticsearch"
  internalPort: 9300
  image:
    repository: "ibmcom/elasticsearch"
    tag: "5.5.1"
  initImage:
    repository: "ibmcom/icp-initcontainer"
    tag: "1.0.0"

  client:
    name: client
    replicas: 1
    serviceType: ClusterIP
    heapSize: "256m"
    restPort: 9200
    antiAffinity: soft

  master:
    name: master
    replicas: 1
    heapSize: "256m"
    antiAffinity: soft

  data:
    name: data
    replicas: 2
    heapSize: "512m"
    antiAffinity: hard
    storage:
      size: 10Gi
      accessModes:
        - ReadWriteOnce
      subPath: ""
      ## If defined, storageClassName: <storageClass>
      ## If set to "-", storageClassName is set to "", which disables dynamic provisioning
      ## If set to null, storageClassName is not included
      storageClass: "manual"

curator:
  name: log-curator
  image:
    repository: "ibmcom/indices-cleaner"
    tag: 0.2
    
  # runs at 23:59 daily
  schedule: "59 23 * * *"
  app:
    unit: days
    count: 1
  monitoring:
    unit: days
    count: 1
  watcher:
    unit: days
    count: 1

xpack:
  monitoring: false
  security: false
  graph: false
  reporting: false
  ml: false
  watcher: false
