prometheus:
  image: 
    name: ibmcom/prometheus
    tag: v1.7.1
  port: 80
  persistentVolume:
    enabled: false
    size: 10Gi
    storageClass: "-"
    
alertmanager:
  image: 
    name: ibmcom/alertmanager
    tag: v0.8.0
  port: 80
  persistentVolume:
    enabled: false
    size: 1Gi
    storageClass: "-"

kubeStateMetrics:
  image: 
    name: ibmcom/kube-state-metrics
    tag: v1.0.0
  port: 80

nodeExporter:
  image: 
    name: ibmcom/node-exporter
    tag: v0.14.0
  port: 9100

grafana:
  image:
    name: "ibmcom/grafana"
    tag: "4.4.3"
  port: 3000
  user: "admin"
  password: "admin"
  prometheusUrl: "http://prometheus-prometheus" 
  persistentVolume:
    enabled: false
    size: 1Gi
    storageClass: "-"

collectdExporter:
  image: 
    name: ibmcom/collectd-exporter
    tag: 0.3.1
  service:
    serviceMetricsPort: 9103
    serviceCollectorPort: 25826

