apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-cassandra
  labels:
     app: {{ template "fullname" . }}-cassandra
     chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
     release: "{{ .Release.Name }}"
     heritage: "{{ .Release.Service }}"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-{{ .Chart.Name }}-cassandra
    spec:
      containers:
        - name: cassandra
          image: {{ .Values.cassandra.image }} 
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 7000
            - containerPort: 9042
            - containerPort: 9160
          env:
            - name: CASSANDRA_CLUSTER_NAME
              value: "LBCLUSTER"
            - name: CASSANDRA_START_RPC
              value: "true"
          volumeMounts:
            - mountPath: /var/lib/cassandra
              name: cassandra-pv-volume
            - mountPath: /etc/cassandra/jvm.options
              name: cassandra-jvm-opts
              subPath: jvm.options
      volumes:
        - name: cassandra-pv-volume
          persistentVolumeClaim:
            {{- if .Values.cassandra.volumeClaim.existingClaimName }}
            claimName: {{ .Values.cassandra.volumeClaim.existingClaimName }}
            {{- else }} 
            claimName: {{ .Release.Name }}-{{ .Values.cassandra.volumeClaim.name }}
            {{- end }}
        - name: cassandra-jvm-opts
          configMap:
            defaultMode: 420
            items:
            - key: cassandra-jvm.options
              path: jvm.options
            name: {{ .Release.Name }}-cassandra-jvm-opts 
