apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-elasticsearch
  labels:
    component: {{ .Release.Name }}-{{ .Chart.Name }}-elasticsearch
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  selector:
    component: {{ .Release.Name }}-{{ .Chart.Name }}-elasticsearch
  ports:
  - name: http
    port: 9200
    protocol: TCP
  type: NodePort
