apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}-kibana
  labels:
    app: {{ .Release.Name }}-{{ .Chart.Name }}-kibana
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 5601
    targetPort: 5601
  selector:
    app: {{ .Release.Name }}-{{ .Chart.Name }}-kibana
