apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-kibana
  labels:
    app: {{ .Release.Name }}-{{ .Chart.Name }}-kibana
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-{{ .Chart.Name }}-kibana
    spec:
      containers:
      - name: kibana
        image: {{ .Values.kibana.image }}  
        imagePullPolicy: IfNotPresent
        env:
          - name: "ELASTICSEARCH_URL"
            value: "http://{{ .Release.Name }}-{{ .Chart.Name }}-elasticsearch:9200"
        ports:
        - containerPort: 5601
          protocol: TCP
