apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-zookeeper
  labels:
    app: {{ .Release.Name }}-{{ .Chart.Name }}-zookeeper
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  type: NodePort
  selector:
    app: {{ .Release.Name }}-{{ .Chart.Name }}-zookeeper
  ports:
    - protocol: TCP
      port: 2181
      targetPort: 2181
