apiVersion: v1
description: IBM Operational Decision Manager for Non-Production
name: ibm-odm-dev
version: 0.9.0
appVersion: 8.9.2
home: https://developer.ibm.com/odm/
icon: https://developer.ibm.com/odm/wp-content/uploads/sites/38/2014/10/ODMMain.png
keywords:
- OperationalDecisionManager
- businessrules
maintainers:
- name: ODMDev
tillerVersion: ">=2.4.0"
