apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-gov-catalog-search-service
  labels:
     app: {{ template "fullname" . }}-gov-catalog-search-service
     chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
     release: "{{ .Release.Name }}"
     heritage: "{{ .Release.Service }}"
spec:
  selector:
    app: {{ template "fullname" . }}-gov-catalog-search-service
  type: NodePort
  ports:
  - name: http
    protocol: TCP
    port: 9080
    targetPort: 9080
