apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}-haproxy
  labels:
    app: {{ template "fullname" . }}-haproxy
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  selector:
    app: {{ template "fullname" . }}-haproxy
  type: NodePort
  ports:
  - name: https
    protocol: TCP
    port: 443
    targetPort: 443
    nodePort: {{ .Values.haproxy.service.httpsNodePort }}

