apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}-shop4info-demoapp
  labels:
     app: {{ template "fullname" . }}-shop4info-demoapp
     chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
     release: "{{ .Release.Name }}"
     heritage: "{{ .Release.Service }}"
spec:
  selector:
    app: {{ template "fullname" . }}-shop4info-demoapp
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
      nodePort: {{ .Values.shop4infoApp.service.httpsNodePort }}
  type: NodePort
