apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}-shop4info-server
  labels:
     app: {{ template "fullname" . }}-shop4info-server
     chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
     release: "{{ .Release.Name }}"
     heritage: "{{ .Release.Service }}"
spec:
  type: NodePort
  selector:
    app: {{ template "fullname" . }}-shop4info-server
  ports:
    - name: http
      protocol: TCP
      port: 9080
      targetPort: 9080
    - name: https
      protocol: TCP
      port: 9443
      targetPort: 9443
