## Metadata for <PRODUCNAME> configuration
## This metadata is used to augment the value.yaml to drive IPC UI for configuration of the Helm chart installation

## Arch metadata for github.com charts
## comment out or remove if github.ibm chart
arch:
  __metadata:
    label: "Architecture scheduling preferences"
  amd64:
    __metadata:
      name: "amd64"
      label: "amd64"
      description: "Architecture preference for target worker node."
      type: "string"
      immutable: false
      required: false
      options:
      - label: "0 - Do not use"
        value: "0 - Do not use"
      - label: "1 - Least preferred"
        value: "1 - Least preferred"
      - label: "2 - No preference"
        value: "2 - No preference"
      - label: "3 - Most preferred"
        value: "3 - Most preferred"
  ppc64le:
    __metadata:
      name: "ppc64le"
      label: "ppc64le"
      description: "Architecture preference for target worker node."
      type: "string"
      immutable: false
      required: false
      options:
      - label: "0 - Do not use"
        value: "0 - Do not use"
      - label: "1 - Least preferred"
        value: "1 - Least preferred"
      - label: "2 - No preference"
        value: "2 - No preference"
      - label: "3 - Most preferred"
        value: "3 - Most preferred"

## Arch example metadata for ppa charts
## remove the arch comment and use the following for PPA charts, can be removed if github.ibm chart
#arch:
#  __metadata:
#    name: "Architecture"
#    label: "Worker node architecture"
#    description: "Worker node architecture to deploy to. The helm chart will try to detect the architecture based on the master node. Choose an explicit architecture here to override it."
#    type: "string"
#    immutable: "false"
#    required: false
#    options:
#      - label: "amd64"
#        value: "amd64"
#      - label: "ppc64le"
#        value: "ppc64le"
#      - label: "s390x"
#        value: "s390x"


## Image configuration metadata
image:
  repository:
    __metadata:
      name: "repository"
      label: "repository"
      description: "Docker image location"
      type: "string"
      immutable: false
      required: true
  pullPolicy:
    __metadata:
      name: "pullPolicy"
      label: "Docker image pull policy"
      description: "Always, Never, or IfNotPresent. Defaults to Always"
      type: "string"
      immutable: false
      required: true
      options:
      - label: "Always"
        value: "Always"
      - label: "Never"
        value: "Never"
      - label: "IfNotPresent"
        value: "IfNotPresent"
  tag:
    __metadata:
      name: "Docker image Tag"
      label: "Docker image Tag"
      description: "Docker image Tag"
      type: "string"
      immutable: false
      required: true

cluster:
    productName:
      __metadata:
        name: "productName"
        label: "Name of the product"
        description: "Deployment product name - optional field dependent on workload"
        type: "string"
        immutable: true
        required: false
    productVersion:
      __metadata:
        name: "productVersion"
        label: "Version of the product"
        description: "Deployment product version - optional field dependent on workload"
        type: "string"
        immutable: true
        required: false
    productID:
      __metadata:
        name: "productID"
        label: "ID of the product"
        description: "Deployment product ID - optional field dependent on workload"
        type: "string"
        immutable: true
        required: false
    pvc:
        size:
          __metadata:
            name: "size"
            label: "Size of shared storage"
            description: "Deployment storage size - optional field dependent on workload"
            type: "string"
            immutable: true
            required: false
        useDynamicProvisioning:
          __metadata:
            name: "useDynamicProvisioning"
            label: "If use dynamic storage provisioning"
            description: "Deployment use dynamic provisioning - optional field dependent on workload"
            type: "bool"
            immutable: true
            required: false
        storageClassName:
          __metadata:
            name: "storageClassName"
            label: "Class of shared storage"
            description: "Deployment storage class - optional field dependent on workload"
            type: "string"
            immutable: true
            required: false
        existingClaimName:
          __metadata:
            name: "existingClaimName"
            label: "Claim name of shared storage"
            description: "Deployment storage claim name - optional field dependent on workload"
            type: "string"
            immutable: true
            required: false
        selector:
            label:
              __metadata:
                name: "label"
                label: "label"
                description: "Deployment selector label - optional field dependent on workload"
                type: "string"
                immutable: true
                required: false
            value:
              __metadata:
                name: "value"
                label: "value"
                description: "Deployment selector value - optional field dependent on workload"
                type: "string"
                immutable: true
                required: false

master:
    replicaCount:
      __metadata:
        name: "replicaCount"
        label: "Replica Count"
        description: "Deployment replicaCount - optional field dependent on workload"
        type: "number"
        immutable: false
        required: false
    uiName:
      __metadata:
        name: "uiName"
        label: "WEB GUI service name"
        description: "Deployment WEB GUI service name - optional field dependent on workload"
        type: "string"
        immutable: false
        required: false
    uiProto:
      __metadata:
        name: "uiProto"
        label: "Protocol"
        description: "Deployment WEB GUI service protocol - optional field dependent on workload"
        type: "string"
        immutable: false
        required: false
    uiPort:
      __metadata:
        name: "uiPort"
        label: "Port"
        description: "Deployment WEB GUI service port - optional field dependent on workload"
        type: "number"
        immutable: false
        required: false
    uiTargetPort:
      __metadata:
        name: "uiTargetPort"
        label: "Target port"
        description: "Deployment WEB GUI service target port - optional field dependent on workload"
        type: "number"
        immutable: false
        required: false
    egoRestName:
      __metadata:
        name: "egoRestName"
        label: "EGO REST service name"
        description: "Deployment EGO REST service name - optional field dependent on workload"
        type: "string"
        immutable: false
        reqegoResred: false
    egoRestProto:
      __metadata:
        name: "egoRestProto"
        label: "Protocol"
        description: "Deployment EGO REST service protocol - optional field dependent on workload"
        type: "string"
        immutable: false
        required: false
    egoRestPort:
      __metadata:
        name: "egoRestPort"
        label: "Port"
        description: "Deployment EGO REST service port - optional field dependent on workload"
        type: "number"
        immutable: false
        required: false
    egoRestTargetPort:
      __metadata:
        name: "egoRestTargetPort"
        label: "Target port"
        description: "Deployment EGO REST service target port - optional field dependent on workload"
        type: "number"
        immutable: false
        required: false
    symRestName:
      __metadata:
        name: "symRestName"
        label: "SYM REST service name"
        description: "Deployment SYM REST service name - optional field dependent on workload"
        type: "string"
        immutable: false
        reqegoResred: false
    symRestProto:
      __metadata:
        name: "symRestProto"
        label: "Protocol"
        description: "Deployment SYM REST service protocol - optional field dependent on workload"
        type: "string"
        immutable: false
        required: false
    symRestPort:
      __metadata:
        name: "symRestPort"
        label: "Port"
        description: "Deployment SYM REST service port - optional field dependent on workload"
        type: "number"
        immutable: false
        required: false
    symRestTargetPort:
      __metadata:
        name: "symRestTargetPort"
        label: "Target port"
        description: "Deployment SYM REST service target port - optional field dependent on workload"
        type: "number"
        immutable: false
        required: false
    resources:
      __metadata:
        label: "Resources"
      requests:
        cpu:
          __metadata:
            label: "CPU request"
            description: "The requested CPU"
            type: "string"
            required: true
        memory:
          __metadata:
            label: "Memory request"
            description: "The memory request"
            type: "string"
            required: true
      limits:
        cpu:
          __metadata:
            label: "CPU limit"
            description: "The CPU limit"
            type: "string"
            required: true
        memory:
          __metadata:
            label: "Memory limit"
            description: "The memory limit"
            type: "string"
            required: true

compute:
    replicaCount:
      __metadata:
        name: "replicaCount"
        label: "Replica Count"
        description: "Deployment replicaCount - optional field dependent on workload"
        type: "number"
        immutable: false
        required: false
    resources:
      __metadata:
        label: "Resources"
      requests:
        cpu:
          __metadata:
            label: "CPU request"
            description: "The requested CPU"
            type: "string"
            required: true
        memory:
          __metadata:
            label: "Memory request"
            description: "The memory request"
            type: "string"
            required: true
      limits:
        cpu:
          __metadata:
            label: "CPU limit"
            description: "The CPU limit"
            type: "string"
            required: true
        memory:
          __metadata:
            label: "Memory limit"
            description: "The memeory limit"
            type: "string"
            required: true
    minReplicas:
      __metadata:
        name: "minReplicas"
        label: "Min replicas"
        description: "Deployment minReplicas - optional field dependent on workload"
        type: "number"
        immutable: false
        required: false
    maxReplicas:
      __metadata:
        name: "maxReplicas"
        label: "Max replicas"
        description: "Deployment maxReplicas - optional field dependent on workload"
        type: "number"
        immutable: false
        required: false
    targetCPUUtilizationPercentage:
      __metadata:
        name: "targetCPUUtilizationPercentage"
        label: "Target CPU Utilization Percentage"
        description: "Deployment targetCPUUtilizationPercentage - optional field dependent on workload"
        type: "number"
        immutable: false
        required: false

client:
    replicaCount:
      __metadata:
        name: "replicaCount"
        label: "Replica Count"
        description: "Deployment replicaCount - optional field dependent on workload"
        type: "number"
        immutable: false
        required: false
    sshName:
      __metadata:
        name: "sshName"
        label: "SSH service name"
        description: "Deployment SSH service name - optional field dependent on workload"
        type: "string"
        immutable: false
        required: false
    sshProto:
      __metadata:
        name: "sshProto"
        label: "Protocol"
        description: "Deployment SSH service protocol - optional field dependent on workload"
        type: "string"
        immutable: false
        required: false
    sshPort:
      __metadata:
        name: "sshPort"
        label: "Port"
        description: "Deployment SSH service port - optional field dependent on workload"
        type: "number"
        immutable: false
        required: false
    sshTargetPort:
      __metadata:
        name: "sshTargetPort"
        label: "Target port"
        description: "Deployment SSH service target port - optional field dependent on workload"
        type: "number"
        immutable: false
        required: false
    resources:
      __metadata:
        label: "Resources"
      requests:
        cpu:
          __metadata:
            label: "CPU request"
            description: "The requested CPU"
            type: "string"
            required: true
        memory:
          __metadata:
            label: "Memory request"
            description: "The memory request"
            type: "string"
            required: true
      limits:
        cpu:
          __metadata:
            label: "CPU limit"
            description: "The CPU limit"
            type: "string"
            required: true
        memory:
          __metadata:
            label: "Memory limit"
            description: "The memory limit"
            type: "string"
            required: true
