## Metadata for IBM Spectrum Symphony configuration
## This metadata is used to augment the value.yaml file to drive configuration of the Helm chart installation from the UI

## Image configuration metadata
image:
  __metadata:
    label: "Docker image"
  repository:
    __metadata:
      label: "Repository"
      description: "Repository for the IBM Spectrum Symphony image"
      type: "string"
      immutable: false
      required: true
  tag:
    __metadata:
      label: "Tag"
      description: "Tag for the IBM Spectrum Symphony image"
      type: "string"
      immutable: false
      required: true
  pullPolicy:
    __metadata:
      label: "Pull policy"
      description: "Always, Never, or IfNotPresent. Defaults to Always."
      type: "string"
      immutable: false
      required: true
      options:
      - label: "Always"
        value: "Always"
      - label: "Never"
        value: "Never"
      - label: "IfNotPresent"
        value: "IfNotPresent"

## Arch metadata for github.com charts
## comment out or remove if github.ibm chart
arch:
  __metadata:
    label: "Architecture scheduling preferences"
  amd64:
    __metadata:
      label: "AMD64"
      description: "Architecture preference for target worker node"
      type: "string"
      immutable: true
      required: false
      options:
      - label: "0 - Do not use"
        value: "0 - Do not use"
      - label: "1 - Least preferred"
        value: "1 - Least preferred"
      - label: "2 - No preference"
        value: "2 - No preference"
      - label: "3 - Most preferred"
        value: "3 - Most preferred"
  ppc64le:
    __metadata:
      label: "PPC64LE"
      description: "Architecture preference for target worker node"
      type: "string"
      immutable: true
      required: false
      options:
      - label: "0 - Do not use"
        value: "0 - Do not use"
      - label: "1 - Least preferred"
        value: "1 - Least preferred"
      - label: "2 - No preference"
        value: "2 - No preference"
      - label: "3 - Most preferred"
        value: "3 - Most preferred"

cluster:
  __metadata:
    label: "Cluster configuration"
  clusterName:
    __metadata:
      label: "Cluster name"
      description: "Name of the IBM Spectrum Symphony cluster"
      type: "string"
      immutable: true
      required: false
  enableSSHD:
    __metadata:
      label: "Enable SSH daemon"
      description: "Enable SSH daemon on cluster nodes"
      type: "boolean"
      immutable: true
      required: false
  pvc:
    __metadata:
      label: "Persistent volume claim"
    size:
      __metadata:
        label: "Size of shared storage"
        description: "Size of shared storage for deployment - optional field dependent on workload"
        type: "string"
        immutable: true
        required: false
    useDynamicProvisioning:
      __metadata:
        label: "Use dynamic storage provisioning"
        description: "Use dynamic provisioning for shared storage"
        type: "boolean"
        immutable: "false"
        required: true
    storageClassName:
      __metadata:
        label: "Class of shared storage"
        description: "Name of the shared storage class"
        type: "string"
        immutable: true
        required: false
    existingClaimName:
      __metadata:
        label: "Claim name of shared storage"
        description: "Name of the existing shared storage claim"
        type: "string"
        immutable: true
        required: false
    selector:
      label:
        __metadata:
          label: "Claim selector label"
          description: "Selector label for claim"
          type: "string"
          immutable: true
          required: false
      value:
        __metadata:
          label: "Claim selector value"
          description: "Selector value for claim"
          type: "string"
          immutable: true
          required: false

master:
  __metadata:
    label: "Management hosts"
  replicaCount:
    __metadata:
      label: "Replica count"
      description: "Number of deployment replicas - optional field dependent on workload"
      type: "number"
      immutable: false
      required: false
  regenSSLCert:
    __metadata:
      label: "Regenerate SSL certificate"
      description: "Regenerate SSL certificate using new host name and domain"
      type: "boolean"
      required: false
  uiEnabled:
    __metadata:
      label: "Enable WEB GUI service"
      description: "Enable WEB GUI service"
      type: "boolean"
      required: false
  egoRestEnabled:
    __metadata:
      label: "Enable EGO REST service"
      description: "Enable EGO REST service"
      type: "boolean"
      required: true
  symRestEnabled:
    __metadata:
      label: "Enable SYM REST service"
      description: "Enable SYM REST service"
      type: "boolean"
      required: false
  resources:
    requests:
      cpu:
        __metadata:
          label: "CPU request"
          description: "CPU resource request on master"
          type: "string"
          required: true
      memory:
        __metadata:
          label: "Memory request"
          description: "Memory resource request on master"
          type: "string"
          required: true
    limits:
      cpu:
        __metadata:
          label: "CPU limit"
          description: "CPU resource limit on master"
          type: "string"
          required: true
      memory:
        __metadata:
          label: "Memory limit"
          description: "Memory resource limit on master"
          type: "string"
          required: true

compute:
  __metadata:
    label: "Compute hosts"
  replicaCount:
    __metadata:
      label: "Replica count"
      description: "Number of deployment replicas on compute"
      type: "number"
      immutable: false
      required: false
  resources:
    __metadata:
      label: "Resources"
    requests:
      cpu:
        __metadata:
          label: "CPU request"
          description: "CPU resource request on compute"
          type: "string"
          required: true
      memory:
        __metadata:
          label: "Memory request"
          description: "Memory resource request on compute"
          type: "string"
          required: true
    limits:
      cpu:
        __metadata:
          label: "CPU limit"
          description: "CPU resource limit on compute"
          type: "string"
          required: true
      memory:
        __metadata:
          label: "Memory limit"
          description: "Memory resource limit on compute"
          type: "string"
          required: true
  minReplicas:
    __metadata:
      label: "Min replicas"
      description: "Minimum number of deployment replicas - optional field dependent on workload"
      type: "number"
      immutable: false
      required: false
  maxReplicas:
    __metadata:
      label: "Max replicas"
      description: "Maximum number of deployment replicas - optional field dependent on workload"
      type: "number"
      immutable: false
      required: false
  usePodAutoscaler:
    __metadata:
      label: "Enable compute hosts horizontal pod autoscaler"
      description: "Enable horizontal autoscaling for compute host pod"
      type: "boolean"
      immutable: false
      required: false
  targetCPUUtilizationPercentage:
    __metadata:
      label: "Target CPU utilization percentage for autoscaler"
      description: "Target CPU utilization percentage when horizontal autoscaling is enabled for compute host pod"
      type: "number"
      immutable: false
      required: false

client:
  __metadata:
    label: "Client hosts"
  replicaCount:
    __metadata:
      label: "Replica count"
      description: "Number of deployment replicas on client"
      type: "number"
      immutable: false
      required: false
  resources:
    __metadata:
      label: "Resources"
    requests:
      cpu:
        __metadata:
          label: "CPU request"
          description: "CPU resource request on client"
          type: "string"
          required: true
      memory:
        __metadata:
          label: "Memory request"
          description: "Memory resource request on client"
          type: "string"
          required: true
    limits:
      cpu:
        __metadata:
          label: "CPU limit"
          description: "CPU resource limit on client"
          type: "string"
          required: true
      memory:
        __metadata:
          label: "Memory limit"
          description: "Memory resource limit on client"
          type: "string"
          required: true
