###############################################################################
######################## IBM Spectrum Symphony. ###############################
###############################################################################

deprecated: true

###############################################################################
## Common image variables
###############################################################################
image:
  repository: ibmcom/spectrum-symphony
  tag: latest
  ## Specify an imagePullPolicy - Always, Never, or IfNotPresent. Defaults to Always.
  pullPolicy: IfNotPresent

###############################################################################
## for github.com charts
###############################################################################
# Specify architecture (amd64, ppc64le, s390x) and weight to be
# used for scheduling as follows:
#   0 - Do not use
#   1 - Least preferred
#   2 - No preference
#   3 - Most preferred
## comment out or remove if github.ibm chart
arch:
  amd64: "2 - No preference"
  ppc64le: "2 - No preference"

cluster:
  clusterName: "Symphony"
  enableSSHD: false
#  productName: "IBM Spectrum Symphony"
#  productVersion: "7.2.0.2"
# name, ibm product #, version, license, counter
#  productID: "IBMSpectrumSymphony_5725G86_7202_CE_000"
  pvc:
    size: 5Gi
    useDynamicProvisioning: true
    # Specify the storageClassName you want to use.
    # If you don't specify a storageClassName, it will use the default <what is the default?>.
    storageClassName: ""
    # Specify the name of the existing claim to be used by your application.
    # An empty string means don't use an existing claim.
    existingClaimName: ""
    # If you are not using dynamic provisioning, you can use selectors to
    # refine the binding process. You cannot specify a selector for dynamic provisioning.
    selector:
      label: ""
      value: ""

master:
  replicaCount: 1
  resources:
    requests:
      cpu: 2
      memory: 2048Mi
    limits:
      cpu: 2
      memory: 2048Mi
  regenSSLCert: false
  uiEnabled: true
  egoRestEnabled: false
  symRestEnabled: false

compute:
  replicaCount: 1
  resources:
    requests:
      cpu: 1
      memory: 1024Mi
    limits:
      cpu: 1
      memory: 1024Mi
  minReplicas: 1
  maxReplicas: 64
  usePodAutoscaler: true
  targetCPUUtilizationPercentage: 70

client:
  replicaCount: 1
  resources:
    requests:
      cpu: 1
      memory: 1024Mi
    limits:
      cpu: 1
      memory: 1024Mi
