image:
  repository: ibmcom/mq
  tag: 9
service:
  name: qmgr
  type: ClusterIP
queuemanager:
  name: qm1
resources:
  storage:
    size: 2Gi
    class: 
  limits:
    cpu: 100m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 512Mi
