address:
  virtualIp: ""
  eventstoreNode: ""
disk:
  storagePath: "/ibm"
  computePath: "/ibm"

ibmEsPvc:
  name: "ibm-es-pvc"
  persistence:
    existingClaimName: ""
    storageClassName: "glusterfs-distributed"
    size: "100Gi"

ibm-dsx-dev:
  image:
    pullPolicy: "IfNotPresent"
  persistence:
    useDynamicProvisioning: true
  userHomePvc:
    persistence:
      existingClaimName: ""
      storageClassName: "glusterfs-distributed"
      size: "10Gi"
  sparkMetricsPvc:
    persistence:
      existingClaimName: ""
      storageClassName: "glusterfs-distributed"
      size: "50Gi"
