apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ template "prometheus.fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: prometheus
    release: {{ .Release.Name }}
  name: {{ template "prometheus.fullname" . }}-alertrules
data:
{{- include .Values.prometheus.alertRuleFiles . | indent 2 }}