apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ template "prometheus.fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: alertmanager
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  name: {{ template "prometheus.fullname" . }}-alertmanager
spec:
  ports:
    - name: web
      port: {{ .Values.alertmanager.port }}
      protocol: TCP
      targetPort: 9093
  selector:
    app: {{ template "prometheus.fullname" . }}
    release: {{ .Release.Name }}
  type: "NodePort"
