apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ template "prometheus.fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: alertmanager
    release: {{ .Release.Name }}
  name: {{ template "prometheus.fullname" . }}-alertmanager
data:
{{- include .Values.alertmanager.configFiles . | indent 2 }}
