apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ template "prometheus.fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: alertmanager
    release: {{ .Release.Name }}
  name: {{ template "prometheus.fullname" . }}-alertmanager
data:
  alertmanager.yml: |-
    global:
      slack_api_url: 'https://hooks.slack.com/services/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'
      smtp_smarthost: 'smtp.gmail.com:587'
      smtp_from: 'k8s.alertmanager@gmail.com'
      smtp_auth_username: 'k8s.alertmanager@gmail.com'
      smtp_auth_password: 'k8sAdmin'
      #pagerduty_url: ''

    receivers:
      - name: default-receiver
        slack_configs:
        - channel: '#prometheus_alert_dev'
          send_resolved: true

      - name: slack_priv_cl
        slack_configs:
        - channel: '#prometheus_alert_dev'
          send_resolved: true

      - name: email_priv_cl
        email_configs:
        - to: 'k8s.alertmanager@gmail.com'

      - name: pagerduty_priv_cl
       # pagerduty_configs:
       # - service_key: ''
        slack_configs:
        - channel: '#prometheus_alert_dev'
          send_resolved: true

    route:
      receiver: default-receiver
      routes:
      - match:
          severity: slack
        receiver: slack_priv_cl
      - match:
          severity: email
        receiver: email_priv_cl
      - match:
          severity: critical
        receiver: pagerduty_priv_cl
