apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ template "grafana.fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  name: {{ template "grafana.fullname" . }}-entry-config
data:
  entrypoint.sh: |
    #!/bin/sh
    mkdir /etc/dashboards
    cp -f /var/lib/grafana/dashboards/*.json /etc/dashboards/
    /run.sh