apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: 'true'
  labels:
    app: {{ template "prometheus.fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: kubestatemetrics
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  name: {{ template "prometheus.fullname" . }}-kubestatemetrics
spec:
  ports:
    - name: http
      port: {{ .Values.kubeStateMetrics.port }}
      protocol: TCP
      targetPort: 8080
  selector:
    app: {{ template "prometheus.fullname" . }}
    component: kubestatemetrics
    release: {{ .Release.Name }}
  type: "NodePort"
