apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: {{ template "prometheus.fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: kubestatemetrics
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  name: {{ template "prometheus.fullname" . }}-kubestatemetrics
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ template "prometheus.fullname" . }}
        component: kubestatemetrics
        release: {{ .Release.Name }}
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                - amd64
      containers:
        - name: kubestatemetrics
          image: {{ .Values.kubeStateMetrics.image.name }}:{{ .Values.kubeStateMetrics.image.tag }}
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 8080
          resources: {}

