apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: 'true'
  labels:
    app: {{ template "prometheus.fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: nodeexporter
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  name: {{ template "prometheus.fullname" . }}-nodeexporter
spec:
  ports:
    - name: metrics
      port: {{ .Values.nodeExporter.port }}
      protocol: TCP
      targetPort: 9100
  selector:
    app: {{ template "prometheus.fullname" . }}
    component: nodeexporter
    release: {{ .Release.Name }}
  type: "NodePort"
