apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ template "prometheus.fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: prometheus
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  name: {{ template "prometheus.fullname" . }}
spec:
  ports:
    - name: http
      port: {{ .Values.prometheus.port }}
      protocol: TCP
      targetPort: 9090
  selector:
    app: {{ template "prometheus.fullname" . }}
    component: prometheus
    release: {{ .Release.Name }}
  type: "NodePort"
