apiVersion: batch/v1
kind: Job
metadata:
  name: secret-generator-deploy
  labels:
    app: {{ template "fullname" . }}  
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"  
spec:
  template:
    metadata:
      name: secret-generator-deploy
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
      - name: secret-generator-deploy
{{ if .Values.SecretGenerator }}
  {{ if .Values.SecretGenerator.Image }}
    {{ if .Values.SecretGenerator.ImageTag }}
        image: "{{.Values.SecretGenerator.Image}}:{{.Values.SecretGenerator.ImageTag}}"
    {{ end}}
  {{ end }}
  {{ if .Values.SecretGenerator.ImagePullSecret }}
    {{ if .Values.SecretGenerator.ImagePullSecret.Name }}
      imagePullSecrets:
        - name: {{ .Values.SecretGenerator.ImagePullSecret.Name }}
    {{end }}
  {{ end }}
{{ else }}
        image: ibmcom/mb-tools:latest
{{ end }}
      restartPolicy: Never

