apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "elasticsearch.fullname" . }}-config
data:
  master.yml: |-
    cluster.name: "{{ .Values.elasticsearch.name }}"
    network.host: 0.0.0.0
    discovery.zen.ping.unicast.hosts: {{ .Values.elasticsearch.master.name }}-discovery
    discovery.zen.minimum_master_nodes: {{ .Values.elasticsearch.master.replicas }}
    xpack.security.enabled: {{ .Values.xpack.security }}
    node.master: true
    node.data: false
    http.enabled: false

  data.yml: |-
    cluster.name: "{{ .Values.elasticsearch.name }}"
    network.host: 0.0.0.0
    discovery.zen.ping.unicast.hosts: {{ .Values.elasticsearch.master.name }}-discovery
    discovery.zen.minimum_master_nodes: {{ .Values.elasticsearch.master.replicas }}
    xpack.security.enabled: {{ .Values.xpack.security }}
    node.master: false
    node.data: true
    http.enabled: false

  client.yml: |-
    cluster.name: "{{ .Values.elasticsearch.name }}"
    network.host: 0.0.0.0
    discovery.zen.ping.unicast.hosts: {{ .Values.elasticsearch.master.name }}-discovery
    discovery.zen.minimum_master_nodes: {{ .Values.elasticsearch.master.replicas }}
    xpack.security.enabled: {{ .Values.xpack.security }}
    node.master: false
    node.data: false
    http.enabled: true
