apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "elasticsearch.fullname" . }}-pvc
  labels:
    app: {{ template "elasticsearch.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "{{ .Values.elasticsearch.data.name }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
spec:
  accessModes:
{{- range .Values.elasticsearch.data.storage.accessModes }}
    - {{ . | quote }}
{{- end }}
  resources:
    requests:
      storage: {{ .Values.elasticsearch.data.storage.size | quote }}
{{- if not (eq "null" .Values.elasticsearch.data.storage.storageClass) }}
{{- if (eq "-" .Values.elasticsearch.data.storage.storageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: "{{ .Values.elasticsearch.data.storage.storageClass }}"
{{- end }}
{{- end }}
