apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ template "filebeat.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "{{ .Values.filebeat.name }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
  name: {{ template "filebeat.fullname" . }}-config
data:
{{ toYaml .Values.filebeat.serverConfigFile | indent 2 }}
