apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "kibana.fullname" . }}-config
data:
  kibana.yml: |-
    server.name: kibana
    server.host: "0"
    elasticsearch.url: "http://{{ .Values.elasticsearch.name }}:{{ .Values.elasticsearch.client.restPort }}"
    xpack.monitoring.enabled: {{ .Values.xpack.monitoring }}
    xpack.security.enabled: {{ .Values.xpack.security }}
    xpack.graph.enabled: {{ .Values.xpack.graph }}
    xpack.reporting.enabled: {{ .Values.xpack.reporting }}
    xpack.ml.enabled: {{ .Values.xpack.ml }}
