
## bluadmin password variable 
BLUADMPASS:
  password: "changemeplease"

persistentVolume:
  useDynamicProvisioning: false

persistentVolumeClaimSettings1:
  storageClassName: ""
persistentVolumeClaimSettings2:
  existingClaimName: ""
persistentVolumeClaimSettings3:
  size: 25Gi

resources:
  requests:
    memory: 8Gi
    cpu: 1000m
