{{ if (not .Values.persistentVolumeClaimSettings2.existingClaimName) -}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "fullname" . }}-pvc1
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  {{- if .Values.persistentVolume.useDynamicProvisioning }}
  storageClassName: {{ default nil .Values.persistentVolumeClaimSettings1.storageClassName | quote }}
  {{- else }}
  storageClassName: ""
  {{- end }}

  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: {{ .Values.persistentVolumeClaimSettings3.size | quote }}
{{- end }}
